# Generated by Django 3.0.5 on 2020-04-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1_titile', models.CharField(max_length=60)),
                ('question_1_description', models.TextField()),
                ('question_1_input', models.CharField(max_length=500)),
                ('question_1_output', models.CharField(max_length=400)),
                ('question_1_sample_1', models.CharField(max_length=10)),
                ('question_1_sample_2', models.CharField(max_length=10)),
                ('question_1_sample_3', models.CharField(max_length=10)),
                ('question_1_sample_4', models.CharField(max_length=10)),
                ('question_2_titile', models.CharField(max_length=60)),
                ('question_2_description', models.TextField()),
                ('question_2_input', models.CharField(max_length=500)),
                ('question_2_output', models.CharField(max_length=400)),
                ('question_2_sample_1', models.CharField(max_length=10)),
                ('question_2_sample_2', models.CharField(max_length=10)),
                ('question_2_sample_3', models.CharField(max_length=10)),
                ('question_2_sample_4', models.CharField(max_length=10)),
                ('question_3_titile', models.CharField(max_length=60)),
                ('question_3_description', models.TextField()),
                ('question_3_input', models.CharField(max_length=500)),
                ('question_3_output', models.CharField(max_length=400)),
                ('question_3_sample_1', models.CharField(max_length=10)),
                ('question_3_sample_2', models.CharField(max_length=10)),
                ('question_3_sample_3', models.CharField(max_length=10)),
                ('question_3_sample_4', models.CharField(max_length=10)),
            ],
        ),
    ]
