# Generated by Django 3.0.5 on 2020-04-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_2_description',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_input',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_output',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_sample_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_sample_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_sample_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_sample_4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_2_titile',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_description',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_input',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_output',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_sample_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_sample_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_sample_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_sample_4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_3_titile',
        ),
    ]
