# Generated by Django 3.0.5 on 2020-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200414_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_1_sample_1',
            field=models.CharField(max_length=500),
        ),
    ]
