# Generated by Django 3.0.5 on 2020-04-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20200411_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Date_of_Birth',
        ),
    ]
