# Generated by Django 3.0.5 on 2020-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_emailconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='kumar_tiwari_1'),
        ),
    ]
