# Generated by Django 3.0.5 on 2020-04-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
